[package]
name = "serry-derive"
description = "Derive macros for Serry."
version = "0.1.0"
license = "Apache-2.0"
repository = "https://github.com/tecc/serry"
authors = ["tecc"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0"
quote = "^1.0"
syn = "^2.0"
